# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20171122_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
