# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171122_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_obj',
            field=models.ForeignKey(blank=True, help_text='请在用户正式成为学员后给该用户创建账户！', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
    ]
