# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20171213_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_student_index', '可以访问学生主页面'), ('can_access_stu_detail', '可以访问学生详细信息'))},
        ),
    ]
